.TH CACHEDEL "1" "March 2013" "cachedel" ""
.SH NAME
cachedel \- drop pagecache for a file
.SH SYNOPSIS
cachedel [\-n <n>] \fBfile\fR
.SH OPTIONS
.TP
\fB\-n <n>\fR "Repeat system call"
Will call posix_fadvise(POSIX_FADV_DONTNEED) \fB<n>\fR in a row.
.SH DESCRIPTION
Call posix_fadvise(POSIX_FADV_DONTNEED) on file.
