#!/bin/sh
NOCACHE_PATH=$(dirname "$0")
libnocache="$NOCACHE_PATH/nocache.so"

if [ -n "$LD_PRELOAD" ]; then
    export LD_PRELOAD="$libnocache $LD_PRELOAD"
else
    export LD_PRELOAD="$libnocache"
fi

if [ "$1" = "-n" ]; then
    export NOCACHE_NR_FADVISE="$2"
    shift 2
fi

exec "$@"
