#!/bin/sh
NOCACHE_PATH=$(dirname "$0")
libnocache="$NOCACHE_PATH/nocache.so"

export LD_PRELOAD="$libnocache $LD_PRELOAD"

if [ "$1" = "-n" ]; then
    export NOCACHE_NR_FADVISE="$2"
    shift 2
fi

if [ "$1" = "-n" ]; then
    export NOCACHE_NR_FADVISE="$2"
    shift 2
fi

exec "$@"
